= Spring Security - 인증 API
jeon3029 <taejjeon@gmail.com>
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:toc:
:hardbreaks:
// images:
:image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_1.png
:image-url2: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_2.png
:image-url3: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_3.png
:image-url4: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_4.png
:image-url5: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_5.png
:image-url6: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_6.png
:image-url7: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/spring_security/img/img2_7.png

Spring Security 02-Form : {author}.

== Basic Form Security

.WebSecurityConfigurerAdapter
[source,java]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
				.authorizeRequests()
        .anyRequest().authenticated();
		http
        .formLogin();
	}
}
----


== UsernamePasswordAuthenticationFilter

image::{image-url1}[UsernamePasswordAuthenticationFilter,800]

- 인증이 완료된 객체는 `SecurityContextHolder.getContext().getAuthenticate()` 를 통해 호출 할 수 있음

.AbstractAuthenticationProcessingFilter
[source,java]
----
protected void successfulAuthentication(HttpServletRequest request,....){
	//....
	SecurityContextHolder.getContext().setAuthentication(authResult);
}

----


=== FilterChainProxy

image::{image-url2}[FilterChainProxy,400]

- 각 필터는 `FilterChainProxy` 에 의해 순서대로 등록하고 있음

== Logout Filter

.configure
[source,java]
----
public class SecurityConfig extends WebSecurityConfigurerAdapter {
  @Override
	protected void configure(HttpSecurity http) throws Exception {
	http.logout()
		.logoutUrl("/logout")
		.logoutSuccessUrl("login")
		.deleteCookies("JSESSIONID","remember-me")
		.addLogoutHandler(new LogoutHandler() {

	  	@Override
		public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication) {
			HttpSession session = request.getSession();
			session.invalidate();
		  }
		})
		.logoutSuccessHandler(new LogoutSuccessHandler() {

		  @Override
		  public void onLogoutSuccess(HttpServletRequest request, HttpServletResponse response,
			  Authentication authentication) throws IOException, ServletException {
				response.sendRedirect("/login");
		  }
		});
	}
}
----

image::{image-url3}[LogoutFilter,800]


== RememberMeAuthenticationFilter

[source,java]
----
http
      .rememberMe()
      .rememberMeParameter("remember")
      .tokenValiditySeconds(3600)
      .alwaysRemember(false)
      .userDetailsService(userDetailsService)
      ;
----

image::{image-url4}[saved cookies]

- remember-me 쿠키를 통해 JSESSIONID 가 없어도 인증 가능(저장)

=== Filter 세부 동작

image::{image-url5}[Remember me 인증,800]

== AnonymousAuthenticationFilter

image::{image-url6}[AnonymousAuthenticationFilter,800]

[source,java]
----
public void doFilter(...){
	if (SecurityContextHolder.getContext().getAuthentication() == null) {
		SecurityContextHolder.getContext().setAuthentication(
					createAuthentication((HttpServletRequest) req));
		//익명 객체라는 기본적인 정보를 담아 저장
		//...
	}
}
----

image::{image-url7}[익명 객체 정보,500]

- 참고
. `AbstractSecurityInterceptor`
* getAuthentication()으로 리소스 접근 허용여부 판단
. `AuthenticationTrustResolverImpl`
* 익명객체 판단 로직

== 동시 세션 제어

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http.sessionManagement()
	.maximumSessions(1)                 // 최대 허용 가능 세션 수 , -1 : 무제한 로그인 세션 허용
	.maxSessionsPreventsLogin(true) // 동시 로그인 차단함,  false : 기존 세션 만료(default)
	.invalidSessionUrl("/invalid")       // 세션이 유효하지 않을 때 이동 할 페이지
	.expiredUrl("/expired ")  	        // 세션이 만료된 경우 이동 할 페이지
	.sessionFixation().changeSessionId() // 기본값
		// none, migrateSession, newSession
	.sessionCreationPolicy(SessionCreationPolicy. If_Required )
		//SessionCreationPolicy. Always 		:  스프링 시큐리티가 항상 세션 생성
		//SessionCreationPolicy. If_Required 	:  스프링 시큐리티가 필요 시 생성(기본값)
		//SessionCreationPolicy. Never   		:  스프링 시큐리티가 생성하지 않지만 이미 존재하면 사용
		//SessionCreationPolicy. Stateless	 	:  스프링 시큐리티가 생성하지 않고 존재해도 사용하지 않음
}
----


