= 01.JPA 소개
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:toc:
:hardbreaks:
:fn-link1: footnote:[]

== JPA(Java Persistent API)

하이버네이트 오픈소스 ORM 프레임워크가 나온 후 자바빈이 버려지고 하이버네이트, 이클립스링크등의 ORM 프레임워크로 자바 ORM 표준을 정한것이 JPA 이다.

기존 엔티티빈이 EJB 컨테이너에 의존하던것에 비해 POJOfootnote:[참고 : https://ko.wikipedia.org/wiki/Plain_Old_Java_Object] 방식 프레임워크로 개발되었으며, 이로인해 Java EE 뿐 아니라 JAVA SE 에서도 사용 가능하며 활용도가 높다. JPA는 사용자가 원하는 퍼시스턴스 프로바이더 구현체를 선택해서 사용할 수 있다.

=== 왜 JPA를 사용해야 하는가?

====
* 생산성 : 지루하고 반복적인 CRUD 코드를 직접 작성하지 않아도 된다.
* 유지보수 : 엔티티에 필드를 하나만 추가해줘도 등록, 수정, 조회 자동으로 매핑 된다.
* 패러다임의 불일치 해결 : 관계형 DB로 객체지향적인 코딩이 가능해 진다.
* 성능 : 한번 조회한건 캐시를 사용함으로 똑같은걸 2번 조회 하지 않는다.(1차캐시)
* 데이터 접근 추상화와 벤더 독립성 : 방언을 통해 자유자제로 다른 DB로 변경이 가능 하다.
====


== 용어 설명

=== ORM(Object Relational Mapping)
관계형 데이터베이스의 데이터를 자동으로 매핑해 주는 것을 의미한다. 데이터 모델과 OOP의 불일치를 해결하기 위해 등장했으며, SQL의 절차적이고 순차적인 접근이 아닌 객체지향적인 접근을 가능하게 한다. 

ORM 프레임워크로는 이 페이지에서 다루는 JPA를 비롯해 Hibernate 가 대표적이며, 장단점은 다음과 같다.

====
.장점
* 객체지향적인 코드 작성이 가능하다.
* 직관성
* 비즈니스 로직에 집중
* 재사용성 및 유지보수 편의가 증가한다
* DBMS 밴더에 독립적
* SQL 자동 생성
* 데이터 모델과 객체간의 차이 해결
* Java 기능/특성 활용이 가능하다.
* 매핑된 데이터는 자바 클래스 이기 때문에 클래스의 기능을 활용할 수 있다.
** ex) 상속, new, equal&hashCode 등의 언어 특성, 편의기능
   

.단점
* 데이터 모델의 복잡도에 비례해 난이도가 증가한다.
* 사용의 편의성으로 인해 무분별한 데이터 모델링을 하게 될 수 있다.
* 성능 저하, 일관성, 정합성
* 대형 쿼리 구현시 별도 튜닝이 필요한 경우가 종종 발생한다.
* 순수 ORM 프레임워크에서 제공하는 기능의 한계
* DBMS 고유 기능을 활용하기 어렵다.
* 경우에 따라 ERD 테이블 개수보다 더 많은 엔티티 클래스가 만들어 진다. 
* 자바의 OOP 관점 설계로 인한 부작용
====


== Reference

https://www.inflearn.com/course/ORM-JPA-Basic/dashboard[자바 ORM 표준 JPA 프로그래밍 - 기본편^]
https://kji6252.github.io/2016/08/03/jpa-basic-01/index.html[JPA 소개]
https://mydevstorage.tistory.com/5[JPA 기본 개념]