= 02.JPA 시작(Hello JPA)
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:toc:
:hardbreaks:
:image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img2_1.png
:image-url2: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img2_2.png

== 프로젝트 생성

=== H2 Database

====
.http://www.h2database.com/
* 최고의 실습용 DB 
* 가볍다.(1.5M)
* 웹용 쿼리툴 제공
* MySQL, Oracle 데이터베이스 시뮬레이션 기능 시퀀스, AUTO INCREMENT 기능 지원
====

=== Maven 

====
.https://maven.apache.org/
* 자바 라이브러리, 빌드 관리
* 라이브러리 자동 다운로드 및 의존성 관리
====

==== 프로젝트 생성

maven project 생성 이후 디펜덴시 주입

.pom.xml
[source,xml]
----
<dependencies>
		<!-- JPA 하이버네이트 -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>5.6.14.Final</version>
		</dependency>
		<!-- H2 데이터베이스 -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>2.1.214</version>
		</dependency>
	</dependencies>
----
사용하는 버전은 강의의 버전과 다른데, 스프링부트 2.7.9 호환 버전으로 설치 함
https://docs.spring.io/spring-boot/docs/2.7.9-SNAPSHOT/reference/html/dependency-versions.html#appendix.dependency-versions

.resources/META-INF/persistence.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.2"
			 xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd">
	<persistence-unit name="hello">
		<properties>
			<!-- 필수 속성 -->
			<property name="javax.persistence.jdbc.driver" value="org.h2.Driver"/>
			<property name="javax.persistence.jdbc.user" value="sa"/>
			<property name="javax.persistence.jdbc.password" value=""/>
			<property name="javax.persistence.jdbc.url" value="jdbc:h2:tcp://localhost/~/test"/>
			<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect"/>
			<!-- 옵션 -->
			<property name="hibernate.show_sql" value="true"/>
			<property name="hibernate.format_sql" value="true"/>
			<property name="hibernate.use_sql_comments" value="true"/>
			<!--<property name="hibernate.hbm2ddl.auto" value="create" />-->
		</properties>
	</persistence-unit>
</persistence>
----
====
* `value="org.hibernate.dialect.H2Dialect"``
* 방언: SQL 표준을 지키지 않는 특정 데이터베이스만의 고유한 기능
** H2 : org.hibernate.dialect.H2Dialect
** Oracle 10g : org.hibernate.dialect.Oracle10gDialect 
** MySQL : org.hibernate.dialect.MySQL5InnoDBDialect
** 하이버네이트는 40가지 이상의 데이터베이스 방언 지원
====
image::{image-url1}[Dialect : jpa 데이터베이스 방언,800]


== 어플리케이션 개발

=== JPA 구동 방식
image::{image-url2}[JPA 구동 방식,800]

.JPA 인스턴스 초기화
[source, java]
----
public class JpaMain {
	public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("hello");
		EntityManager em = emf.createEntityManager();
		em.close();
		emf.close();
		
	}
}
----
기본적인 jpa 동작의 이상 유무를 확인할 수 있다.

.sql 초기 설정, h2 database
[source,sql]
----
create table Member(
  id bigint not null,
  name varchar(255),
  primary key (id)
);
----
.Member.java
[source,java]
----
@Entity
public class Member {
  @Id
  private long id;
  private String name;
  //Getter,Setter
}
----

.저장 삭제 변경 등  기본 CRUD
[source,java]
----
EntityTransaction tr = em.getTransaction();
tr.begin();
try {
  //insert
  Member member = new Member();
  member.setName("Jane");
  member.setId(2L);
  em.persist(member);

  //select / update
  //객체의 값만 바꾸어도 커밋하기 전에 체크해서 바뀌었으면 update 처리를 해 줌
  //jpa 짱짱맨
  Member findMember = em.find(Member.class, 1L);
  findMember.setName("changed");
  
  //delete
  em.remove(findMember);

  tr.commit();
} catch (Exception e) {
  tr.rollback();
  System.out.println("transaction error : " + e);
} finally {
  em.close();
}
----
* 기본적으로 JPA 모든 변경은 트랜잭션 안에서 실행
* `EntityManagerFactory` 는 하나만 생성해서 애플리케이션 전체에서 공유
* `EntityManager` 는 스레드간 공유되면 안됨.(사용하고 close)

=== JPQL 소개

실무에서 많이 쓰임

* 가장 단순한 조회 방식
** EntityManager.find()
** 객체 그래프 탐색(a.getB().getC())
* 나이가 18살 이상인 회원을 모두 조회하고 싶다면?

.JPQL Example
[source,java]
----
//약간 스타일이 다름, 객체를 조회하는 방식
//oracle 로 바뀌면 그대로 번역 해 줌
List<Member> result = em.createQuery("select m from Member as m", Member.class)
    .setFirstResult(5).setMaxResults(8)
    .getResultList();
for (Member m : result) {
  System.out.println("m.getName() = " + m.getName());
}
----

.JPQL
* JPA 를 사용하면 엔티티 객체를 중심으로 개발
* 문제는 검색 쿼리
* 모든 DB 데이터를 객체로 변환해서 검색하는 것은 불가능
* 필요한 데이터만 불러 오려면 검색 조건이 포함된 SQL 쿼리가 필요함
* 테이블이 아닌 객체를 대상으로 검색하는 객체 지향 쿼리;
* 특정 데이터베이스에 의존하지 않음
* 객체 지향 SQL
** 뒤에서 더 다룰 예정

















