= 05.Relational Mapping
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:toc:
:hardbreaks:
:image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img5_1.png
:image-url2: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img5_2.png
:image-url3: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img5_3.png
:image-url4: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img5_4.png


== 용어

. 방향(Direction)
+ 
단방향, 양방향
. 다중성(Multiplicity)
+
다대일(N:1), 일대다(1:N), 일대일(1:1), 다대다(N:M) 이해
. 연관관계의 주인(Owner)
+
객체 양방향 연관관계는 관리 주인 이 필요

== 단방향 연관관계

예제 : 회원, 팀, 다대일 관계

.객체를 테이블에 맞추어 모델링 한 경우
image::{image-url1}[연관관계 없는 객체,700]

.참조 대신에 외래키 그래도 사용
[source,java]
----
@Entity
public class Member {
  @Id @GeneratedValue
  private Long id; 

  @Column(name = "USERNAME") 
  private String name;

  @Column(name = "TEAM_ID") 
  private String teamId;
  }
}
@Entity
public class Team{
  @Id @GeneratedValue
  private Long id; 

  private String name;
}
----

.외래키 식별자를 직접 다룸
[source,java]
----
//팀 저장
Team team = new Team();
team.setName("TeamA"); 
em.persist(team);

//회원 저장
Member member = new Member();
member.setName("member1");
member.setTeamId(team.getId());
em.persist(member);
//조회
Member findMember = em.find(Member.class, member.getId());
//연관관계가 없음
Team findTeam = em.find(Team.class, team.getId());
----

.객체 연관관계를 사용하는 케이스(객체 지향 모델링)
image::{image-url2}[]

[source,java]
----
@Column(name = "TEAM_ID")
//private Long teamId;

@ManyToOne
@JoinColumn(name = "TEAM_ID")
private Team team;
----

.연관관계 저장
[source,java]
----
//팀 저장
Team team = new Team();
team.setName("TeamA");
em.persist(team);
//회원 저장
Member member = new Member(); 
member.setName("member1");
member.setTeam(team); //단방향 연관관계 설정, 참조 저장
em.persist(member);

//조회
Member findMember = em.find(Member.class, member.getId());
//참조를 사용해서 연관관계 조회
Team findTeam = findMember.getTeam();
// 새로운 팀B
Team teamB = new Team();
teamB.setName("TeamB");i
em.persist(teamB);

// 회원1에 새로운 팀B 설정
member.setTeam(teamB);
----

== 양방향 연관관계

.양방향 매핑
image::{image-url3}[양방향 매핑,700]

.Team.java
[source,java]
----
@Entity
public class Team{
  @Id @GeneratedValue
  private Long id; 

  private String name;
  @OneToMany(mappedBy="team")//중요!!
  List<Member> members = new ArrayList<Member();
}

//조회
Team findTeam = em.find(Team.class, team.getId());
int memberSize = findTeam.getMembers().size(); //역방향 조회
----

.mappedBy
. 처음에는 이해하기 어렵다
. 양방향 관계는 사실 양방향 관계가 아니라 서로 다른 단 뱡향 관계 2개다.
. 객체를 양방향으로 참조하려면 단방향 연관관계를 2개 만들어 야 한다

.테이블 관점
* 테이블은 외래 키 하나로 두 테이블의 연관관계를 관리
* MEMBER.TEAM_ID 외래 키 하나로 양방향 연관관계 가짐  (양쪽으로 조인할 수 있다.)

=== 누구를 주인으로?

.외래키가 있는 곳을 주인으로 정해라
image::{image-url4}[]

== 양방향 매핑 시 자주하는 실수

. 연관관계의 주인에 값을 입력하지 않음
[source,java]
----
Team team = new Team();
team.setName("TeamA");
em.persist(team);
Member member = new Member();
member.setName("member1");
//역방향(주인이 아닌 방향)만 연관관계 설정
team.getMembers().add(member);
em.persist(member);
----
. 연관관계의 주인에 값을 입력해야 한다
[source,java]
----
Team team = new Team();
team.setName("TeamA");
em.persist(team);

Member member = new Member();
member.setName("member1");
team.getMembers().add(member); 
//연관관계의 주인에 값 설정
member.setTeam(team); //**!!
em.persist(member);
----
.. 순수한 객체 관계를 고려하면 항상 양쪽다 값을 입력해야 한다.

.순수 객체 상태를 고려해서 항상 양쪽에 값을 설정하자
. 연관관계 편의 메소드를 생성하자
. 양방향 매핑시에 무한 루프를 조심하자
.. 예: toString(), lombok, JSON 생성 라이브러리

=== 양방향 매핑 정리

. 방향 매핑만으로도 이미 연관관계 매핑은 완a료
. 양방향 매핑은 반대 방향으로 조회(객체 그래프 탐색) 기능이 추 가된 것 뿐
. JPQL에서 역방향으로 탐색할 일이 많음
. 단방향 매핑을 잘 하고 양방향은 필요할 때 추가해도 됨 (테이블에 영향을 주지 않음)

INFO: 연관관계의 주인은 외래 키의 위치를 기준으로 정해야함