= 08.Proxy
:reproducible:
:listing-caption: Source
:source-highlighter: rouge
:toc:
:hardbreaks:
:image-url1: https://cdn.jsdelivr.net/gh/jeon3029/learning_spring@master/jpa_basic/img/img8_1.png


== 연관되어 있는 엔티티를 함께 조회해야 할까?

다음과 같은 상황
====
.Member
* String username
* Team team

.Team
* String name
====

.Ex1. 멤버, 팀 모두 출력
[source,java]
----
public void printUserAndTeam(String memberId) {
  Member member = em.find(Member.class, memberId);
  Team team = member.getTeam();
  System.out.println("회원 이름: " + member.getUsername());
  System.out.println("소속팀: " + team.getName()); 
}
----
.Ex2. 멤바랑 팀 모두 출력
[source,java]
----
public void printUser(String memberId) {
  Member member = em.find(Member.class, memberId);
  Team team = member.getTeam();
  System.out.println("회원 이름: " + member.getUsername());
}
----


== 프록시 기초

* em.find()  VS em.getReference()
** em.find : 데이터베이스에서 실제 엔티티 조회
** em.getReference() : 데이터베이스 조회를 미루는 프록시 엔티티객체 조회

.프록시 객체
* 실제 클래스 상속받아서 만듦
* 사용하는 입장에서는 구분하지 않고 사용
* 프록시 객체를 호출하면 실제 객체의 메소드 호출

[source,java]
----
Member member = em.getReference(Member.class, "id1");
member.getName();
----

image::{image-url1}[프록시객체 초기화,700]


.프록시의 특징
* 프록시 객체는 원본 엔티티를 상속받음, 따라서 타입 체크시 주의해야함 (== 비 교 실패, 대신 instance of 사용)
* 영속성 컨텍스트에 찾는 엔티티가 이미 있으면 em.getReference()를 호출해 도 실제 엔티티 반환
* 영속성 컨텍스트의 도움을 받을 수 없는 `준영속 상태`일 때, 프록시를 초기화하면 문제 발생
(하이버네이트는 org.hibernate.LazyInitializationException 예외를 터트림)

== 즉시로딩과 지연로딩

.지연로딩 LAZY 사용해서 프록시로 조회
[source,java]
----
@Entity
public class Member {
  private String name; 
  @ManyToOne(fetch = FetchType.LAZY) 
  @JoinColumn(name = "TEAM_ID")
  private Team team;
  //..
}
----

.함께 많이 사용한다면? 즉시로딩 사용 가능
[source,java]
----
@ManyToOne(fetch = FetchType.EAGER) //** 
@JoinColumn(name = "TEAM_ID")
private Team team;
----

=== 프록시와 즉시로딩 주의
* 가급적 지연 로딩만 사용(특히 실무에서)
* 즉시 로딩을 적용하면 예상하지 못한 SQL이 발생
* 즉시 로딩은 JPQL에서 N+1 문제를 일으킨다.
+
NOTE: N+1 문제:조회 시 1개의 쿼리를 생각하고 설계를 했으나 나오지 않아도 되는 조회의 쿼리가 N개가 더 발생하는 문제.

** EAGER 로 같이 참조하는 엔티티가 여러개일경우 쿼리가 의도치 않게 여러개 나가게 됨
* @ManyToOne, @OneToOne은 기본이 즉시 로딩 
** -> LAZY로 설정
* @OneToMany, @ManyToMany는 기본이 지연 로딩

[source,java]
----
List<Member> memberList = em.createQuery("select m from Member  m",Member.class)
					.getResultList();
//이 경우에 멤버 조인 1개, 팀 쿼리 n 개가 나올 수 있음(N+1 쿼리)


List<Member> memberList = em.createQuery("select m from Member m join fetch m.team",Member.class)
					.getResultList();
// LAZY 로 바꾸고 fetch join 등을 활용 하는 방법이 있음
----

.결론...
====
실무에서 즉시 로딩을 사용하지 마라!
JPQL fetch 조인이나, 엔티티 그래프 기능을 사용해라!
====


== 영속성 전이: CASCADE

특정 엔티티를 영속 상태로 만들 때 연관된 엔티티도 함께 영속 상태로 만들도 싶을 때

* 예: 부모 엔티티를 저장할 때 자식 엔티티도 함께 저장.

[source,java]
----
@OneToMany(mappedBy="parent", cascade=CascadeType.PERSIST)
----

.영속성 전의 주의할 점
====
영속성 전이는 연관관계를 매핑하는 것과 아무 관련이 없음
엔티티를 영속화할 때 연관된 엔티티도 함께 영속화하는 편리함 을 제공할 뿐
====

.CASCADE의 종류
====
ALL: 모두 적용
PERSIST: 영속
REMOVE: 삭제
MERGE: 병합
REFRESH: REFRESH 
DETACH: DETACH
====

.다음 경우에사용하면 편리함
* 단일 엔티티에 종속적일 때, (라이프 사이클이 똑같을 때)
* 단일 소유자일 때


== 고아객체

고아 객체 제거: 부모 엔티티와 연관관계가 끊어진 자식 엔티티 를 자동으로 삭제

* orphanRemoval = true
[source,java]
----
Parent parent1 = em.find(Parent.class, id); parent1.getChildren().remove(0);
//자식 엔티티를 컬렉션에서 제거
----

.고아객체 주의
====
참조하는 곳이 하나일 때 사용해야함!
특정엔티티가개인소유할때사용
개념적으로 부모를 제거하면 자식은 고아가 된다
====

.영속성전이 + 고아객체, 생명주기
====
CascadeType.ALL + orphanRemovel=true

* 두 옵션을 모두 활성화 하면 부모 엔티티를 통해서 자식의 생명 주기를 관리할 수 있음
====